#!/bin/bash

set -e
DIR=`git rev-parse --git-dir`

if [ -e "$DIR/tags" ]
    then
        rm "$DIR/tags"
fi

ctags-exuberant -f "$DIR/tags" \
    -h \".php\" -R \
    --langmap=PHP:.php \
    --exclude=.git \
    --exclude=data \
    --exclude=node_modules \
    --exclude=public \
    --exclude=test \
    --exclude=*.js \
    --exclude=*.lock \
    --exclude=*.phar \
    --exclude=*.svn \
    --exclude=*.swp \
    --exclude=*.vim \
    --tag-relative=yes \
    --python-kinds=-i \
    --PHP-kinds=-v \
    --regex-PHP='/interface ([^ ]*)/\1/c/' \
    --regex-PHP='/(abstract\s+|final\s+).*function\s+\&?\s*([^ (]+)/\2/f/'
